require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssertsController do

  # This should return the minimal set of attributes required to create a valid
  # Assert. As you add validations to Assert, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "assertName" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssertsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all asserts as @asserts" do
      assert = Assert.create! valid_attributes
      get :index, {}, valid_session
      assigns(:asserts).should eq([assert])
    end
  end

  describe "GET show" do
    it "assigns the requested assert as @assert" do
      assert = Assert.create! valid_attributes
      get :show, {:id => assert.to_param}, valid_session
      assigns(:assert).should eq(assert)
    end
  end

  describe "GET new" do
    it "assigns a new assert as @assert" do
      get :new, {}, valid_session
      assigns(:assert).should be_a_new(Assert)
    end
  end

  describe "GET edit" do
    it "assigns the requested assert as @assert" do
      assert = Assert.create! valid_attributes
      get :edit, {:id => assert.to_param}, valid_session
      assigns(:assert).should eq(assert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Assert" do
        expect {
          post :create, {:assert => valid_attributes}, valid_session
        }.to change(Assert, :count).by(1)
      end

      it "assigns a newly created assert as @assert" do
        post :create, {:assert => valid_attributes}, valid_session
        assigns(:assert).should be_a(Assert)
        assigns(:assert).should be_persisted
      end

      it "redirects to the created assert" do
        post :create, {:assert => valid_attributes}, valid_session
        response.should redirect_to(Assert.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assert as @assert" do
        # Trigger the behavior that occurs when invalid params are submitted
        Assert.any_instance.stub(:save).and_return(false)
        post :create, {:assert => { "assertName" => "invalid value" }}, valid_session
        assigns(:assert).should be_a_new(Assert)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Assert.any_instance.stub(:save).and_return(false)
        post :create, {:assert => { "assertName" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assert" do
        assert = Assert.create! valid_attributes
        # Assuming there are no other asserts in the database, this
        # specifies that the Assert created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Assert.any_instance.should_receive(:update_attributes).with({ "assertName" => "MyString" })
        put :update, {:id => assert.to_param, :assert => { "assertName" => "MyString" }}, valid_session
      end

      it "assigns the requested assert as @assert" do
        assert = Assert.create! valid_attributes
        put :update, {:id => assert.to_param, :assert => valid_attributes}, valid_session
        assigns(:assert).should eq(assert)
      end

      it "redirects to the assert" do
        assert = Assert.create! valid_attributes
        put :update, {:id => assert.to_param, :assert => valid_attributes}, valid_session
        response.should redirect_to(assert)
      end
    end

    describe "with invalid params" do
      it "assigns the assert as @assert" do
        assert = Assert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Assert.any_instance.stub(:save).and_return(false)
        put :update, {:id => assert.to_param, :assert => { "assertName" => "invalid value" }}, valid_session
        assigns(:assert).should eq(assert)
      end

      it "re-renders the 'edit' template" do
        assert = Assert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Assert.any_instance.stub(:save).and_return(false)
        put :update, {:id => assert.to_param, :assert => { "assertName" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assert" do
      assert = Assert.create! valid_attributes
      expect {
        delete :destroy, {:id => assert.to_param}, valid_session
      }.to change(Assert, :count).by(-1)
    end

    it "redirects to the asserts list" do
      assert = Assert.create! valid_attributes
      delete :destroy, {:id => assert.to_param}, valid_session
      response.should redirect_to(asserts_url)
    end
  end

end
